/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package builderdesignpattern;

/**
 *
 * @author 123456789
 */
public class WidgetForm extends javax.swing.JFrame {

    /**
     * Creates new form WidgetForm
     */
    public WidgetForm() {
        initComponents();
    } 
    
    
     public WidgetForm(String FristName, String LastName, String degree, String Seconddegree, String EmailAddress,int phone, String webiste, String Coutry, String State, String City) {
        initComponents();
        FristNamelabel.setText(FristName);
        LastNamelabel.setText(LastName);
        if(Seconddegree!= null )
            degreelabel.setText(Seconddegree);
        else 
            degreelabel.setText(degree);
        
        EmailAddresslabel.setText(EmailAddress);
        phonelabel.setText(phone+"");
        webistelabel.setText(webiste);
        Coutrylabel.setText(Coutry);
        Citylabel.setText(City);
        Statelabel.setText(State);
        
    } 
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FristNamelabel = new javax.swing.JLabel();
        LastNamelabel = new javax.swing.JLabel();
        degreelabel = new javax.swing.JLabel();
        EmailAddresslabel = new javax.swing.JLabel();
        phonelabel = new javax.swing.JLabel();
        webistelabel = new javax.swing.JLabel();
        Coutrylabel = new javax.swing.JLabel();
        Statelabel = new javax.swing.JLabel();
        Citylabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FristNamelabel.setText("jLabel1");

        LastNamelabel.setText("jLabel2");

        degreelabel.setText("jLabel3");

        EmailAddresslabel.setText("jLabel4");

        phonelabel.setText("jLabel5");

        webistelabel.setText("jLabel6");

        Coutrylabel.setText("jLabel7");

        Statelabel.setText("jLabel8");

        Citylabel.setText("jLabel9");

        jLabel10.setText("Address");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FristNamelabel)
                    .addComponent(EmailAddresslabel)
                    .addComponent(jLabel10))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LastNamelabel)
                            .addComponent(phonelabel))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(webistelabel)
                            .addComponent(degreelabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Coutrylabel)
                        .addGap(39, 39, 39)
                        .addComponent(Statelabel)
                        .addGap(18, 18, 18)
                        .addComponent(Citylabel)))
                .addContainerGap(331, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FristNamelabel)
                    .addComponent(LastNamelabel)
                    .addComponent(degreelabel))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailAddresslabel)
                    .addComponent(phonelabel)
                    .addComponent(webistelabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Coutrylabel)
                    .addComponent(Statelabel)
                    .addComponent(Citylabel)
                    .addComponent(jLabel10))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WidgetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WidgetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WidgetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WidgetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WidgetForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Citylabel;
    private javax.swing.JLabel Coutrylabel;
    private javax.swing.JLabel EmailAddresslabel;
    private javax.swing.JLabel FristNamelabel;
    private javax.swing.JLabel LastNamelabel;
    private javax.swing.JLabel Statelabel;
    private javax.swing.JLabel degreelabel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel phonelabel;
    private javax.swing.JLabel webistelabel;
    // End of variables declaration//GEN-END:variables
}
